# Use postgres/example user/password credentials
version: "3.1"

services:
    frontend:
        build: frontend
        ports:
          - '80:80'
    apirest:
        build: apirest
        restart: always
        ports:
            - '8080:8080'

    # auth_api:
    #     build: authAPI
    #     restart: always
    #     ports:
    #         - 8083:8083
    # games_api:
    #     build: gamesAPI
    #     restart: always
    #     ports:
    #         - 8081:8081
    # mongo:
    #     image: mongo
    #     restart: always
    #     ports:
    #         - 27017:27017
    #     environment:
    #         MONGO_INITDB_ROOT_USERNAME: dra
    #         MONGO_INITDB_ROOT_PASSWORD: pass123

    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: pass
            POSTGRES_DB: apiREST
        ports:
             - '5432:5432'
            
    # adminer:
    #     image: adminer
    #     restart: always
    #     ports:
    #         - 8080:8080

volumes:
    data: